apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
      app: my-web-app

spec:
  containers:
    - name: nginx-container
      image: devasria/mysimplewebapplication:latest
      ports:
        - containerPort: 80

